# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedlink',
            name='mobile_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shortenedlink',
            name='shortened',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='shortenedlink',
            name='tablet_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shortenedlink',
            name='url',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
