# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20170124_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedlink',
            name='shortened',
        ),
    ]
